=== fornaciari/BERTective/decour.1/hearing.dtd
<!ELEMENT hearing (header, intro, turn+, conclu?)>
<!ELEMENT header            EMPTY>
<!ELEMENT intro             (#PCDATA)*>
<!ELEMENT turn              (act?|utterance+)*>
<!ELEMENT act               (#PCDATA)>
<!ELEMENT utterance         (#PCDATA|token|ttlemma|ttpos)*>
<!ELEMENT token             (#PCDATA)>
<!ELEMENT ttlemma           (#PCDATA)>
<!ELEMENT ttpos             (#PCDATA)>
<!ELEMENT conclu            (#PCDATA)>
<!ATTLIST header
          idhear         CDATA                                                             #REQUIRED
          idsub          CDATA                                                             #REQUIRED
          sex            (M | F | T)                                                       #REQUIRED
          birtharea      (N | C | S | E)                                                   #REQUIRED
          age            CDATA                                                             #REQUIRED
          study          (E | M | S | U | Ma | D | unk)                                    "unk"
          typesub        (def | vic | defwit | vicwit | thirdwit | pol | expwit)           #REQUIRED>
<!ATTLIST turn
          speaker        (judge | pros | pros2 | law | law2 | viclaw | viclaw2 | pol | pol2 |
                          expwit | def | vic | defwit | vicwit | thirdwit)                 #REQUIRED
          nrgen          NMTOKEN                                                           #REQUIRED
          nrjudge        NMTOKEN                                                           #IMPLIED
          nrpros         NMTOKEN                                                           #IMPLIED
          nrpros2        NMTOKEN                                                           #IMPLIED
          nrlaw          NMTOKEN                                                           #IMPLIED
          nrlaw2         NMTOKEN                                                           #IMPLIED
          nrviclaw       NMTOKEN                                                           #IMPLIED
          nrviclaw2      NMTOKEN                                                           #IMPLIED
          nrpol          NMTOKEN                                                           #IMPLIED
          nrpol2         NMTOKEN                                                           #IMPLIED
          nrsub          NMTOKEN                                                           #IMPLIED>
<!ATTLIST utterance
          class          (true | false | uncertain | x)                                    "x"
          nrgen          NMTOKEN                                                           #REQUIRED
          nrjudge        NMTOKEN                                                           #IMPLIED
          nrpros         NMTOKEN                                                           #IMPLIED
          nrpros2        NMTOKEN                                                           #IMPLIED
          nrlaw          NMTOKEN                                                           #IMPLIED
          nrlaw2         NMTOKEN                                                           #IMPLIED
          nrviclaw       NMTOKEN                                                           #IMPLIED
          nrviclaw2      NMTOKEN                                                           #IMPLIED
          nrpol          NMTOKEN                                                           #IMPLIED
          nrpol2         NMTOKEN                                                           #IMPLIED
          nrsub          NMTOKEN                                                           #IMPLIED>

=== fornaciari/BERTective/decour.1/decour2017.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE hearing SYSTEM "hearing.dtd">
<hearing>
<header idhear="20" idsub="17" sex="F" age="27" birtharea="N" study="unk" typesub="defwit"/>
<intro>GIUDICE MONOCRATICO - DOTT.SSA Stella Polare Helsingor , 00/00/00 Procedimento penale contro Vega Fabio Carlo Amedeo N. 0000/00 R.G. .
Viene introdotto il testimone ; questi viene avvertito dal Giudice dei suoi obblighi e rende la dichiarazione ex Art. 497 C.P.P. Fornisce le generalità : Pollux Antonia , nata a Dublino il 00/00/00 , ivi residente .
</intro>
<turn speaker="judge" nrgen="1" nrjudge="1">
<utterance class="x" nrgen="1" nrjudge="1">Lei conosce l' imputato qui presente , visto che si è girata un attimo a guardare ?<token>lei conosce l' imputato qui presente , visto che si è girata un attimo a guardare ?</token><ttlemma>lei conoscere l' imputato qui presente , visto che si essere girare un attimo a guardare ? </ttlemma><ttpos>PRO:pers VER:fin ART NOUN ADV ADJ PUN NOUN CHE CLI AUX:fin VER:ppast ART NOUN PRE VER:infi SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="2" nrsub="1">
<utterance class="uncertain" nrgen="2" nrsub="1">Io lo conosco , perché abitava vicino al mio ex fidanzato , tanti anni fa .<token>io lo conosco , perché abitava vicino al mio ex fidanzato , tanti anni fa .</token><ttlemma>io lo conoscere , perché abitare vicino al mio ex fidanzato , tanto anno fa . </ttlemma><ttpos>PRO:pers CLI VER:fin PUN WH VER:fin ADJ ARTPRE DET:poss ADJ NOUN PUN DET:indef NOUN ADV SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="3" nrjudge="2">
<utterance class="x" nrgen="3" nrjudge="2">Questo ex fidanzato chi è ?<token>questo ex fidanzato chi è ?</token><ttlemma>questo ex fidanzato chi essere ? </ttlemma><ttpos>DET:demo ADJ NOUN WH VER:fin SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="4" nrsub="2">
<utterance class="uncertain" nrgen="4" nrsub="2">Si chiamava Berengario Denebola , ma stiamo parlando del 1995 o 1996 .<token>si chiamava xxxx xxxxola , ma stiamo parlando del 1995 o 1996 .</token><ttlemma>si chiamare &lt;unknown&gt; &lt;unknown&gt; , ma stare parlare del @card@ o @card@ . </ttlemma><ttpos>CLI VER:fin NOUN ADJ PUN CON VER:fin VER:geru ARTPRE NUM CON NUM SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="5" nrjudge="3">
<utterance class="x" nrgen="5" nrjudge="3">Invece una persona di nome Pier Gian Carlo Deneb chi è ?<token>invece una persona di nome xxxx xxxx xxxx xxxx chi è ?</token><ttlemma>invece una persona di nome &lt;unknown&gt; &lt;unknown&gt; &lt;unknown&gt; &lt;unknown&gt; chi essere ? </ttlemma><ttpos>ADV ART NOUN PRE NOUN ADJ ADJ NOUN ADJ WH VER:fin SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="6" nrsub="3">
<utterance class="true" nrgen="6" nrsub="3">È mio marito .<token>È mio marito .</token><ttlemma>essere mio marito . </ttlemma><ttpos>VER:fin DET:poss NOUN SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="7" nrjudge="4">
<utterance class="x" nrgen="7" nrjudge="4">Lei quando si è sposata ?<token>lei quando si è sposata ?</token><ttlemma>lei quando si essere sposare ? </ttlemma><ttpos>PRO:pers WH CLI AUX:fin VER:ppast SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="8" nrsub="4">
<utterance class="true" nrgen="8" nrsub="4">Nel 2002 .<token>nel 2002 .</token><ttlemma>nel @card@ . </ttlemma><ttpos>ARTPRE NUM SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="9" nrjudge="5">
<utterance class="x" nrgen="9" nrjudge="5">Quindi nel 2000-2001 era già Suo fidanzato ?<token>quindi nel 2000-2001 era già suo fidanzato ?</token><ttlemma>quindi nel @card@ essere già suo fidanzato ? </ttlemma><ttpos>ADV ARTPRE NUM AUX:fin ADV DET:poss NOUN SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="10" nrsub="5">
<utterance class="true" nrgen="10" nrsub="5">Sì .<token>sì .</token><ttlemma>sì . </ttlemma><ttpos>ADV SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="11" nrjudge="6">
<utterance class="x" nrgen="11" nrjudge="6">Stavate insieme , anche convivendo ?<token>stavate insieme , anche convivendo ?</token><ttlemma>stare insieme , anche convivere ? </ttlemma><ttpos>VER:fin ADV PUN ADV VER:geru SENT </ttpos></utterance>
<utterance class="x" nrgen="12" nrjudge="7">Era una convivenza ?<token>era una convivenza ?</token><ttlemma>essere una convivenza ? </ttlemma><ttpos>VER:fin ART NOUN SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="12" nrsub="6">
<utterance class="true" nrgen="13" nrsub="6">Un pò di qua e un pò di là .<token>un pò di qua e un pò di là .</token><ttlemma>un po' di qua e un po' di là . </ttlemma><ttpos>ART PRO:indef PRE ADV CON ART PRO:indef PRE ADV SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="13" nrjudge="7">
<utterance class="x" nrgen="14" nrjudge="8">Lei nel 2000-2001 aveva un cellulare ?<token>lei nel 2000-2001 aveva un cellulare ?</token><ttlemma>lei nel @card@ avere un cellulare ? </ttlemma><ttpos>PRO:pers ARTPRE NUM VER:fin ART NOUN SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="14" nrsub="7">
<utterance class="true" nrgen="15" nrsub="7">Sì .<token>sì .</token><ttlemma>sì . </ttlemma><ttpos>ADV SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="15" nrjudge="8">
<utterance class="x" nrgen="16" nrjudge="9">Questo cellulare lo utilizzava anche il Pier Gian Carlo Deneb ?<token>questo cellulare lo utilizzava anche il xxxx xxxx xxxx xxxx ?</token><ttlemma>questo cellulare lo utilizzare anche il &lt;unknown&gt; &lt;unknown&gt; &lt;unknown&gt; &lt;unknown&gt; ? </ttlemma><ttpos>DET:demo NOUN CLI VER:fin ADV ART NOUN ADJ ADJ NOUN SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="16" nrsub="8">
<utterance class="true" nrgen="17" nrsub="8">Lo usavamo insieme , perché insomma , c' era quello che caricavamo e ...<token>lo usavamo insieme , perché insomma , c' era quello che caricavamo e ...</token><ttlemma>lo usare insieme , perché insomma , c' essere quello che caricare e ... </ttlemma><ttpos>CLI VER:fin ADV PUN WH ADV PUN ADV VER:fin PRO:demo CHE VER:fin CON SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="17" nrjudge="9">
<utterance class="x" nrgen="18" nrjudge="10">Era intestato a Lei , oppure è un telefono che non va nemmeno intestato ?<token>era intestato a lei , oppure è un telefono che non va nemmeno intestato ?</token><ttlemma>essere intestare a lei , oppure essere un telefono che non andare nemmeno intestato ? </ttlemma><ttpos>AUX:fin VER:ppast PRE PRO:pers PUN CON VER:fin ART NOUN CHE NEG VER:fin ADV ADJ SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="18" nrsub="9">
<utterance class="true" nrgen="19" nrsub="9">Io , sinceramente , non mi ricordo molto , perché all' epoca usavo psicofarmaci , Cucu , Tata , quelle cose , quindi ho buchi di memoria , però mi ricordo che i Carabinieri mi avevano chiamata in caserma per ...<token>io , sinceramente , non mi ricordo molto , perché all' epoca usavo psicofarmaci , xxxx , xxxx , quelle cose , quindi ho buchi di memoria , però mi ricordo che i carabinieri mi avevano chiamata in caserma per ...</token><ttlemma>io , sinceramente , non mi ricordare molto , perché all' epoca usare psicofarmaco , &lt;unknown&gt; , &lt;unknown&gt; , quello cosa , quindi avere buco di memoria , però mi ricordare che il carabiniere mi avere chiamare in caserma per ... </ttlemma><ttpos>PRO:pers PUN ADV:mente PUN NEG CLI VER:fin ADV PUN WH ARTPRE NOUN VER:fin NOUN PUN NOUN PUN NOUN PUN DET:demo NOUN PUN ADV VER:fin NOUN PRE NOUN PUN ADV CLI VER:fin CHE ART NOUN CLI AUX:fin VER:ppast PRE NOUN PRE SENT </ttpos></utterance>
<utterance class="true" nrgen="20" nrsub="10">perché mi dissero che c' era un albanese che clonava le schede , che c' era questo numero e che a loro risultava che era mio .<token>perché mi dissero che c' era un albanese che clonava le schede , che c' era questo numero e che a loro risultava che era mio .</token><ttlemma>perché mi dire che c' essere un albanese che clonare la scheda , che c' essere questo numero e che a loro risultare che essere mio . </ttlemma><ttpos>WH CLI VER:fin CHE ADV VER:fin ART ADJ CHE VER:fin ART NOUN PUN CHE ADV VER:fin DET:demo NOUN CON CHE PRE PRO:pers VER:fin CHE VER:fin PRO:poss SENT </ttpos></utterance>
<utterance class="true" nrgen="21" nrsub="11">Era mio , e mi fecero fare una ...<token>era mio , e mi fecero fare una ...</token><ttlemma>essere mio , e mi fare fare una ... </ttlemma><ttpos>VER:fin PRO:poss PUN CON CLI VER2:fin VER:infi ART SENT </ttpos></utterance>
<utterance class="true" nrgen="22" nrsub="12">una deposizione , insomma , che io non conoscevo questo albanese , ed effettivamente non lo conoscevo .<token>una deposizione , insomma , che io non conoscevo questo albanese , ed effettivamente non lo conoscevo .</token><ttlemma>una deposizione , insomma , che io non conoscere questo albanese , ed effettivamente non lo conoscere . </ttlemma><ttpos>ART NOUN PUN ADV PUN CHE PRO:pers NEG VER:fin DET:demo ADJ PUN CON ADV:mente NEG CLI VER:fin SENT </ttpos></utterance></turn>
<turn speaker="judge" nrgen="19" nrjudge="10">
<utterance class="x" nrgen="23" nrjudge="11">All' epoca di questi fatti il Suo attuale marito assumeva sostanze stupefacenti ?<token>all' epoca di questi fatti il suo attuale marito assumeva sostanze stupefacenti ?</token><ttlemma>all' epoca di questo fatto il suo attuale marito assumere sostanza stupefacente ? </ttlemma><ttpos>ARTPRE NOUN PRE DET:demo NOUN ART DET:poss ADJ NOUN VER:fin NOUN ADJ SENT </ttpos></utterance>
<utterance class="x" nrgen="24" nrjudge="12">Aveva bisogno di ...<token>aveva bisogno di ...</token><ttlemma>avere bisogno di ... </ttlemma><ttpos>VER:fin NOUN PRE SENT </ttpos></utterance></turn>
<turn speaker="defwit" nrgen="20" nrsub="10">
